language: go

python:
  - tip

env:
  global:
    - secure: "TnjrQzsv+fuG8f8fuTEPP71/REOLMt9RKhrJFAx+gM4N3gwqt/TayIBS5VXl/c4NmU2/OGUZv6vjHUUOGpztMr7BzfH6Th2nn8BTCwVWI5w8PHKlYKwOldQ/h9KuPrdyzaeGINlFKF8//3K057LdvumV6uYoiL6IdaWHLF7LUk0="

sudo: false

addons:
  apt:
    packages:
      - python-virtualenv

before_install:
  - if [ $TRAVIS_BRANCH = "master" ]; then source publish.sh; prepare; fi

install:
  # dependencies
  - go get github.com/deckarep/golang-set github.com/rainycape/unidecode
  # for test coverage
  - go get github.com/axw/gocov/gocov github.com/mattn/goveralls github.com/tools/godep
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - export PATH=$PATH:$GOPATH/bin

script:
  - go build -v
  - gocov test ./... -covermode count > gocov.json
  - goveralls -service=travis-ci -gocovdata gocov.json
  - go vet
  - PUBLISH=1 ./umi
  - if [ $TRAVIS_BRANCH = "master" ]; then publish; fi

notifications:
  email: false
